### ISSUE TITLE
Change the theme look and feel to match the ScyllaDB website

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/sphinx-scylladb-theme#1056]
Modify the theme to better match the webstie: https://www.scylladb.com/

This is a task for a ScyllaDB designer, so it belongs to the Design_tasks project.

Refs: https://github.com/scylladb/scylladb-docs-homepage/issues/11

@timkoopmans FYI

**Comment by dgarcia360** [comment]
Some other tasks that the designer might want to take into account:

- https://github.com/scylladb/sphinx-scylladb-theme/issues/621
- https://github.com/scylladb/sphinx-scylladb-theme/issues/257
- https://github.com/scylladb/sphinx-scylladb-theme/issues/251
- https://github.com/scylladb/sphinx-scylladb-theme/issues/358
- https://github.com/scylladb/sphinx-scylladb-theme/issues/938
- https://github.com/scylladb/sphinx-scylladb-theme/issues/859

**Comment by dgarcia360** [comment]
Closed by https://github.com/scylladb/sphinx-scylladb-theme/pull/1314
