### ISSUE TITLE
Make it possible to reference different branches on contribute.html

### ISSUE THREAD

**Issue by dkropachev** [scylladb/sphinx-scylladb-theme#1156]
Problem:
Java driver have two major branches where all the development happens:
scylla-3.x
scylla-4.x

So, when user is on the page for driver version `3.7.2.x` and clicking to "Edit this page" or "Create an Issue" they should be redirected to https://github.com/scylladb/java-driver/tree/scylla-3.x
while if they are on `4.12.x` they should be redirected to https://github.com/scylladb/java-driver/tree/scylla-4.x

**Comment by dgarcia360** [comment]
Since Java 4 is now the default branch, this might no longer be necessary. If it is still an issue, we can reopen it.
