### ISSUE TITLE
update scylladb logo

### ISSUE THREAD

**Issue by timkoopmans** [scylladb/sphinx-scylladb-theme#1181]
The ScyllaDB logo has been refreshed, attaching svg
![scylladb-logo-horizontal](https://github.com/user-attachments/assets/ac787758-8ba6-417d-b010-ab5db069baa6)

Also when updating please check the visual center line (horizontal) as the text DOCUMENTATION looks misaligned (may need to adjust padding of logo itself)
![image](https://github.com/user-attachments/assets/182a4021-0578-49e4-8cdb-15683ef983a4)

**Comment by dgarcia360** [comment]
@annastuchlik @kwiato Waiting for your ok to apply this change. We could also update the mascots lib.
