### ISSUE TITLE
redesign the project name link

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/sphinx-scylladb-theme#1200]
We've improved the project name link by transforming it into a link to the project documentation landing page.
However, it looks bad and is not intuitive - it's not clear just by looking at it how it works. 
It should stand out so that it doesn't appear to be part of the page tree. 

![image](https://github.com/user-attachments/assets/c194799a-1f8f-42df-afc5-b7a406eb1be8)

![image](https://github.com/user-attachments/assets/f529da30-f3ab-471d-84c8-b8fbf933a463)

**Comment by dgarcia360** [comment]
Closed by https://github.com/scylladb/sphinx-scylladb-theme/pull/1314
