### ISSUE TITLE
Remove font awesome

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/sphinx-scylladb-theme#1220]
## Motivation

Deprecate Font Awesome now we have custom icons lib.

Also, use lib icons instead of fontawesome for the following extensions:

- https://fontawesome.com/v4/icon/external-link

    https://github.com/scylladb/sphinx-scylladb-theme/blob/566db08dd113c8a919a711d9827465cc82db3977/sphinx_scylladb_theme/extensions/topic_box.py#L87

-  https://fontawesome.com/v4/icon/check (similar one already in lib)

    https://github.com/scylladb/sphinx-scylladb-theme/blob/566db08dd113c8a919a711d9827465cc82db3977/sphinx_scylladb_theme/__init__.py#L78

**Comment by dgarcia360** [comment]
Closes https://github.com/scylladb/sphinx-scylladb-theme/pull/1217

**Comment by dgarcia360** [comment]
More icons missing:

- https://fontawesome.com/v4/icon/external-link

```
a.reference.external:after {
  content: "\f08e";
}
```


- https://fontawesome.com/v4/icon/download
```
a.reference.download:after {
  content: "\f019";
}
```

**Comment by dgarcia360** [comment]
@kwiato Could you please update the font icons lib with the previous icons?

**Comment by kwiato** [comment]
The icons are already there.  :)
Add `@use "sass:map";` at the start of scss file and replace the code
```
a.reference.external:after {
  content: map.get($icons, "newtab");
}

a.reference.download:after {
  content: map.get($icons, "download");
}
```
