### ISSUE TITLE
dark theme does not support the panel box within a raw html directive 

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/sphinx-scylladb-theme#1236]
This looks bad and must be fixed with a patch.
See https://github.com/scylladb/scylladb/issues/20881.

**Comment by dgarcia360** [comment]
Closing, see https://github.com/scylladb/scylladb/issues/20881#issuecomment-2398961600

**Comment by dgarcia360** [comment]
Apply a fix to show harcoded panel box in dark mode in previous version
