### ISSUE TITLE
Opening Sphinx-Substitution-Extensions versions

### ISSUE THREAD

**Issue by tnozicka** [scylladb/sphinx-scylladb-theme#1290]
Currently the project requires `Sphinx-Substitution-Extensions = "^2022.2.16"` which means `(>=2022.2.16,<2023.0.0)` which is quite old and transitively enforce on the other docs projects.

I can't get substitution to work in the code blocks by following https://pypi.org/project/sphinx-substitution-extensions/#toc-entry-8 so I figured this likely needs a bump.

Could you please loosen it to use `>=`?

**Comment by tnozicka** [comment]
I think the new version just tolerates the extra space I was using in some context (`{{ productName }}`) so it's not that pressing and it can't substitute literalincludes anyway.

**Comment by dgarcia360** [comment]
Thanks for reporting this.

We will review this in detail before upgrading.

Related PR: https://github.com/scylladb/sphinx-scylladb-theme/pull/1264
