### ISSUE TITLE
Collapsible navigation

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/sphinx-scylladb-theme#193]
Expanded:

![image](https://user-images.githubusercontent.com/9107969/135753114-347b1256-c5c6-4fee-8f60-42c45b5ade13.png)

Collapsed:

**Option A)**

![image](https://user-images.githubusercontent.com/9107969/135753122-3cc9a51f-b6cc-4a54-9bbd-8cc40552d1b9.png)

**Option B)**

![image](https://user-images.githubusercontent.com/9107969/135753138-f3e8c972-4f65-4f7c-985b-b673a68a73f1.png)

**Comment by dgarcia360** [comment]
@lauranovich @tzach Which option do you prefer? A or B?

**Comment by tzach** [comment]
Option B look inconsistent with A, while C is

**Comment by tzach** [comment]
I like B better because its more minimal. The text should display on hover only.

**Comment by lauranovich** [comment]
B is more consistent with our other screen elements
