### ISSUE TITLE
Theme compile warning

### ISSUE THREAD

**Issue by tzach** [scylladb/sphinx-scylladb-theme#209]
WARNING: error while formatting arguments for sphinx_scylladb_theme.extensions.substitutions.substitution_code_role: type object 'list' has no attribute '_special'

**Comment by dgarcia360** [comment]
The GitHub Actions build does not raise this warning: https://github.com/scylladb/sphinx-scylladb-theme/runs/4150144473?check_suite_focus=true

For this reason, I think it's safe to close this issue. Please open it again if you experience it again.
