### ISSUE TITLE
Contribute Selection - needs a better solution

### ISSUE THREAD

**Issue by lauranovich** [scylladb/sphinx-scylladb-theme#220]
Every repo has it's own thoughts about how to contribute to it.
Docs has a contribution method as well 

So instead of 
How to Contribute -> going to Scylla https://docs.scylladb.com/contribute/ 
it should route to a page specific to the project. 

We can further make this separation clearer by adding:
How to Contribute to Docs ---> links to https://sphinx-theme.scylladb.com/stable/contribute/
How to Contribute to Code --> links to the gitHub repo ( but a md page needs to be created explaining what to do to contribute) - if all projects have a contribute.md file, then we can make a generic link which will always work.

If each maintainer had a generic document - how to contribute - it would be beneficial to them as well - we should have a template they can customize.

**Comment by dgarcia360** [comment]
In the meanwhile, the [contribute page ](https://docs.scylladb.com/contribute/) could add the following note:

> **Contribute to code**
> Read the **CONTRIBUTING.md** file that you will find at the root-level folder of the project.

Contribute to Scylla’s Source Code could be part of the scylla repo CONTRIBUTING.md file.

**Comment by lauranovich** [comment]
the scylla repo already has a contributing.md - the other repos don't

**Comment by tzach** [comment]
Lets try two buttons:
- Report an issue
- Update this page

And remove the Contribute

**Comment by tzach** [comment]
See https://kubernetes.io/docs/home/
