### ISSUE TITLE
Search box round corner

### ISSUE THREAD

**Issue by tzach** [scylladb/sphinx-scylladb-theme#221]
The Download box have round corner, while the search box does not
![image](https://user-images.githubusercontent.com/170200/135448885-28372932-1c12-4214-a9b9-ecf457b35193.png)

**Comment by dgarcia360** [comment]
I can't see the issue:

In the image you shared, the searchbox has a rounded corner:

![image](https://user-images.githubusercontent.com/9107969/135591480-8ef07c79-66d9-4741-ba6c-b0c4fed42cf8.png)

The button and the searchbox both have the same border-radius (4px):

**Button**

![image](https://user-images.githubusercontent.com/9107969/135591270-f6507b14-94b3-4bf8-aa96-18d2f33639e6.png)

**Search box**

![image](https://user-images.githubusercontent.com/9107969/135591616-c1f025b3-1bb4-4c2a-8562-08733df1d924.png)

**Comment by tzach** [comment]
Look like we found the problem: I need to start using glasses ;)
Something in the style of this two seems unmatched to me. Now I'm not sure what.
