### ISSUE TITLE
a few issues with the new theme

### ISSUE THREAD

**Issue by lauranovich** [scylladb/sphinx-scylladb-theme#224]
https://github.com/scylladb/scylla-doc-issues/issues/801
this should be routed to the theme but it opened in the doc issues
please address this link and the other issues inside the issue.

**Comment by dgarcia360** [comment]
It was pointing to scylla-doc-issues because the repo was not open source. https://github.com/scylladb/sphinx-scylladb-theme/pull/225 changed the "Report an Issue" link to `sphinx-scylladb-theme`.

Addressed the issue referenced in https://github.com/scylladb/sphinx-scylladb-theme/pull/226
