### ISSUE TITLE
General use

### ISSUE THREAD

**Issue by elvece** [scylladb/sphinx-scylladb-theme#249]
Not so much an issue as an inquiry: 

But first, love the design of this theme, nice work! 
Is this theme able to be used with any sphinx documentation project? I've been having trouble getting it to work in a default way (mainly using it as an `html_theme` and following the installation steps in the documentation - can elaborate if necessary) 
If so, are the headers/footer easily customizable, or could I work on a contribution that would enable this?

Thanks for your time.

**Comment by tzach** [comment]
This theme is for Scylla Docs, we are not planning to release this theme without Scylla branding.
