### ISSUE TITLE
Table design: gray header looks "disable"

### ISSUE THREAD

**Issue by tzach** [scylladb/sphinx-scylladb-theme#256]
Gray headers hard to read on blue background
![image](https://user-images.githubusercontent.com/170200/144292218-dc79c898-d042-4f73-a4ac-8cec566b7d2d.png)
![image](https://user-images.githubusercontent.com/170200/144292230-65594c6b-1111-4a84-b136-11aecee6877c.png)

**Comment by dgarcia360** [comment]
We could try with a darker gray. For example:

![image](https://user-images.githubusercontent.com/9107969/145094089-0f2abcdc-42af-4911-a0ad-9db2f41d9e87.png)
