### ISSUE TITLE
Text in version selector should be align to menu

### ISSUE THREAD

**Issue by tzach** [scylladb/sphinx-scylladb-theme#257]
The version number (not the box!) should be align to the left menu text
![image](https://user-images.githubusercontent.com/170200/144292961-434a1e87-08de-45a3-9643-8ee4f713169f.png)

**Comment by dgarcia360** [comment]
It's seems common to have the sidebar text and the box aligned.

From Figma:

![image](https://user-images.githubusercontent.com/9107969/145095119-cd2554f2-3cae-4396-9a23-3b29f0aa9937.png)

How others are doing:

![image](https://user-images.githubusercontent.com/9107969/145095248-2631e5d3-2ff0-4fc6-9289-a1b6c5cd7ba2.png)

![image](https://user-images.githubusercontent.com/9107969/145095282-48212648-d139-47b1-ac3a-ac1a8304ae81.png)

![image](https://user-images.githubusercontent.com/9107969/145095380-41a8d7ca-81d5-4a80-8b2e-a09eb5a0b2e9.png)

**Comment by tzach** [comment]
Maybe the difference is the other examples have a clearer border, while in our case the text is much more visible than the box

**Comment by dgarcia360** [comment]
Closed by https://github.com/scylladb/sphinx-scylladb-theme/pull/1314
