### ISSUE TITLE
Update python and js dependencies to the latest version

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/sphinx-scylladb-theme#262]
Related issue https://github.com/scylladb/scylla-manager/issues/2964

**Comment by tzach** [comment]
Can we have a dependency bot for both?

**Comment by dgarcia360** [comment]
- Updated all the dependencies manually in https://github.com/scylladb/sphinx-scylladb-theme/pull/263
- Enabled a dependency bot for github actions, python, and js in https://github.com/scylladb/sphinx-scylladb-theme/blob/master/dependabot.yml
- Added [CodeQL](https://codeql.github.com/) to find vulnerabilities within the code.
