### ISSUE TITLE
Style tables with headings

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/sphinx-scylladb-theme#298]
## Context

Tables with headings look slightly off.

![image](https://user-images.githubusercontent.com/9107969/148183651-dc047e00-6785-4715-bf67-a9e3047f5833.png)

## Proposal

Style the table headings as follows:

![image](https://user-images.githubusercontent.com/9107969/148183955-a6d43934-c25e-4e74-9a70-0e3258d7d68b.png)

**Comment by tzach** [comment]
Any way to make the top header more bold?

**Comment by tzach** [comment]
(not the columns headers)

**Comment by dgarcia360** [comment]
@tzach See https://github.com/scylladb/sphinx-scylladb-theme/issues/256#issuecomment-988209549, what do you think?

**Comment by dgarcia360** [comment]
How about:

![image](https://user-images.githubusercontent.com/9107969/148188317-2e831721-5c69-452a-8bae-7f8fe54b8bee.png)
