### ISSUE TITLE
[Search results page] Style new projects component

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/sphinx-scylladb-theme#299]
## Context

The search page recently added a new component "Projects", which is unstyled:

![image](https://user-images.githubusercontent.com/9107969/148188777-bb21ee72-df33-45de-b4e6-e68ff431e476.png)

## Proposal

- [x] Style the new component:

![image](https://user-images.githubusercontent.com/9107969/148189237-0e4b5575-33cf-4749-a7a8-ce9f4a4ad303.png)

- [x] Remove the results list left padding:

![image](https://user-images.githubusercontent.com/9107969/148189362-e72b8551-4e9c-407f-9ecf-77d8485891b9.png)

**Comment by tzach** [comment]
Very good!
