### ISSUE TITLE
Image types

### ISSUE THREAD

**Issue by kn0wmad** [scylladb/sphinx-scylladb-theme#355]
Hi there, sorry if this is the wrong place to post, but I didn't see any documentation on the image types that can be used.  We are working on a project and wanted to use the 'zoomable' type images, but could only get them to work with .svg format.  This was fine, until we discovered that those images were broken when viewing on some machines (possibly due to vector vs raster differences).  My question is:

Are .svg the only type of image that works in this case?

If so, please consider this issue a feature request for support to other image formats.

**Comment by dgarcia360** [comment]
Hi @kn0wmad, thanks for reporting this issue!

As you find out, it was only working with SVG images.

I've submitted [this fix](https://github.com/scylladb/sphinx-scylladb-theme/pull/362
) to make it work with other formats (e.g. JPG, PNG, GIF, ...).
