### ISSUE TITLE
[feat] Ability to open internal ref in new tab

### ISSUE THREAD

**Issue by kn0wmad** [scylladb/sphinx-scylladb-theme#373]
Thanks @dgarcia360 for the fix on my last issue.  Though of a feature request, not sure what the scope would be:

 I'd like to be able to open an internal reference in a new tab

**Comment by dgarcia360** [comment]
We don't have a use case to support this functionality in this theme.

If you want to modify the theme's behavior, here are the lines that process all the page links and determine if they are external or not to open them on a new window: https://github.com/scylladb/sphinx-scylladb-theme/blob/master/src/js/index.js#L9-L21
