### ISSUE TITLE
[Contents directive] Show more than one level

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/sphinx-scylladb-theme#476]
## Context

The contents directive only shows one level, even if ``:depth:`` attribute is passed. 

For example:

```
.. contents:: 
   :local:
   :depth: 4
```

Renders:

![image](https://user-images.githubusercontent.com/9107969/168837028-a92787a9-2978-45fe-a127-56803d791a45.png)

But it does not render H3, H4, and H5 titles.

## Proposal

- [ ] Edit the CSS to remove this limitation.
- [ ] Propose a new design.

**Comment by annastuchlik** [comment]
@dgarcia360 Let's give up the idea for now.
