### ISSUE TITLE
Remove genindex page

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/sphinx-scylladb-theme#478]
## Context

Remove genindex (auto generated page) or exclude it from search results: https://sphinx-theme.scylladb.com/stable/genindex

Requested by @[annastuchlik](https://github.com/annastuchlik)

**Comment by dgarcia360** [comment]
@annastuchlik Sphinx autogenerates this page, and there is no straightforward way to remove it. It's populated with content if some page of the documentation uses the "index: role](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html?highlight=index#role-index)". Here you can see an example: https://www.sphinx-doc.org/en/master/genindex.html

We could exclude all the URLs containing the string `genindex` URLs containing the string "genindex.html" from the search engine. 

## Steps

1. Sign in to https://cse.expertrec.com/?platform=cse with an account that has admin permissions.
2. Navigate to **crawl-> What to crawl->Filter**
3. Under filter URLs-> Enter URL patterns you want to exclude :  "genindex".
4. Choose **will be ignored**:

![image](https://user-images.githubusercontent.com/9107969/172347393-7b6ae282-24c0-4895-8b87-165088ff1ffc.png)

5. Select **Update**

**Comment by annastuchlik** [comment]
@dgarcia360 Thank you! I've updated the search excludes. I'll verify if it works after the next crawl.

**Comment by annastuchlik** [comment]
The problem has been resolved. Thanks!
![image](https://user-images.githubusercontent.com/37244380/173358569-bf4e292d-3c5d-413c-b67d-ce32ebcbc9a6.png)
