### ISSUE TITLE
Make issue and edit button more visible

### ISSUE THREAD

**Issue by tzach** [scylladb/sphinx-scylladb-theme#621]
I suspect many readers miss the giyhub buttons on the right
I sugget to make them more visable. For example by:
- make the icone / text larger
- run a quick genetle animation fir time you visit the docs
- other?
![image](https://user-images.githubusercontent.com/170200/201866973-826bfe44-c582-4159-b1e5-7ce59efecc57.png)

@annastuchlik @dgarcia360 what do you think?

**Comment by annastuchlik** [comment]
@tzach We can discuss how to improve it, but, to my mind, the buttons are quite visible when we compare them to the buttons in other documentation sets. I've collected some samples to share with you.

**Comment by tzach** [comment]
A developer told me he was not aware of the issue and edit button.

**Comment by dgarcia360** [comment]
Closed by https://github.com/scylladb/sphinx-scylladb-theme/pull/1314
