### ISSUE TITLE
Reset top banner cookie every time we update the banner

### ISSUE THREAD

**Issue by tzach** [scylladb/sphinx-scylladb-theme#639]
PRs like https://github.com/scylladb/scylladb/pull/12189
replace the top banner, but most viewers will not see it, as they already disable the banner it at some point in the past.
We need to reset the cookie every time the banner is updated (which is not often)

**Comment by tzach** [comment]
@annastuchlik FYI

**Comment by dgarcia360** [comment]
I'm not sure I can detect when the banner changes, but I can make the cookie expire a fixed period of time. For example, we could set it to 15 days.

**Comment by tzach** [comment]
30 days is good enougth
