### ISSUE TITLE
Consider removing poetry.lock from .gitignore

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/sphinx-scylladb-theme#849]
This issue is opened to start a discussion per the developer's request in issue https://github.com/scylladb/scylladb/issues/12033.

While checking in lock files is a good practice, the proposed solution may impact, for example, running local previews. We may opt to leave the current solution,  but it's worth discussing what options we have.

**Comment by dgarcia360** [comment]
We propose that each project commits its `poetry.lock` file to the repository, as recommended in https://python-poetry.org/docs/basic-usage/#committing-your-poetrylock-file-to-version-control

### Why

1. **Repeatable builds**: Ensures consistent dependency versions across development and production.

2. **Minimized risk of breakage**: Locks dependencies to prevent issues from unexpected updates, as seen in https://github.com/scylladb/sphinx-scylladb-theme/pull/1157

### Challenges & solutions

- **Distribution flexibility vs. security**: Committing the lock file limits automatic theme updates, favoring stability but reducing flexibility.

     **Proposed solution**: Enable [Dependabot ](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide) on each project to automate dependency updates, targetting our Sphinx packages (sphinx-scylladb, sphinx-scylladb-multiversion).

**Comment by dgarcia360** [comment]
During the upgrade, I noticed that we needed to remove the `poetry update` command from the `make setup` command to ensure that the dependencies defined in `poetry.lock` are used in production builds. I’ve applied this change to most of the upgrade PRs, except for the repositories that have already merged, for which I’ll send a fix:

- [ ] sphinx-theme  
- [ ] scylladb  
- [ ] scylladb-docs-homepage  
- [ ] care-pet  
- [ ] python-driver  
- [ ] cpp-driver  
- [ ] scylla-rust-driver  
- [ ] scylla-cloud-doc
