### ISSUE TITLE
Support glossary tooltips

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/sphinx-scylladb-theme#873]
## Motivation

Show a floating window on the cross references of the documentation pointing to a glossary term.

![image](https://github.com/scylladb/sphinx-scylladb-theme/assets/9107969/b6d7d4b4-ea4e-4ee0-bb1c-ca28b7056e62)

## Inspiration:

https://sphinx-hoverxref.readthedocs.io/en/latest/index.html

**Comment by tzach** [comment]
Nice!
