### ISSUE TITLE
Main menu is missing bullets and uses extra spacing

### ISSUE THREAD

**Issue by tnozicka** [scylladb/sphinx-scylladb-theme#934]
When I was thinking over why I find our operator docs menu (on the left) harder to navigate, compared to other docs out there, it came down to these:
- Spaces between the items are quite large so you don't see as much without scrolling
- Items miss bullet points to visually distinguish them, especially if they are multi-line (probably also the reason why the spacing is so big)

Is there a way to configure this?

As an example, compare the menu of Scylla Operator

![Screenshot from 2023-10-25 09-31-20](https://github.com/scylladb/sphinx-scylladb-theme/assets/11869554/f0ab99d4-1a87-489a-aaf2-9b210cf1f615)

with say Kubernetes docs menu

![Screenshot from 2023-10-25 09-30-43](https://github.com/scylladb/sphinx-scylladb-theme/assets/11869554/8b8ffe2b-9e21-4443-99d6-b290ad697dc0)

**Comment by dgarcia360** [comment]
Closed by https://github.com/scylladb/sphinx-scylladb-theme/pull/1314
