### ISSUE TITLE
Menu items are hard to expand

### ISSUE THREAD

**Issue by tnozicka** [scylladb/sphinx-scylladb-theme#945]
When you want to expand a hierarchical item in the menu without visiting the "dummy" index page, it is extremely tricky to hit the tiny arrow to only expand the menu (5px height)
![Screenshot from 2023-11-29 12-46-55](https://github.com/scylladb/sphinx-scylladb-theme/assets/11869554/a4e2aac6-3673-4fed-94f9-43ba6eadf9c3)

It would be great if the space would be larger.

Even better approach might be to allow getting rid of the dummy index pages and let the items be expanded when clicking on the whole menu item (including the text). Expanding the items is desirable because you avoid the roundtrip to the server to fetch the extra index page. Also the "dummy" index pages usually have the same content as the menu index but often get out of sync ([or they are not pretty](#935)), so some page is missing or they are reordered (like in the screenshot). To cover the case when you want to have in intro to a section, we can always add an item called `Overview` or something like that as the first one in the list.

**Comment by dgarcia360** [comment]
Closed by https://github.com/scylladb/sphinx-scylladb-theme/pull/1314
