### ISSUE TITLE
Collapse to have :open:

### ISSUE THREAD

**Issue by dkropachev** [scylladb/sphinx-scylladb-theme#952]
Can we make [collapse](https://sphinx-toolbox.readthedocs.io/en/stable/extensions/collapse.html) to have same features as
[sphinx-toolbox.collapse](https://github.com/sphinx-toolbox/sphinx-toolbox), particular `:open:` :
```
.. collapse:: Open
    :open:

    This section is open by default.
```

**Comment by dgarcia360** [comment]
The latest version of [sphinx-collapse](https://github.com/scylladb/sphinx-scylladb-theme/pull/1022) includes the possibility of defining it as open.

Usage:

```
.. collapse:: Open
    :open:

    This section is open by default.
 ```
